<a href="https://colab.research.google.com/github/songnee/test/blob/main/5_Reg_CrossValidate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 교차 검증 (Cross Validation)
![](https://velog.velcdn.com/images/newnew_daddy/post/9d55a412-b773-46a2-ba61-d36c87de648f/image.png)
#### 학습중인 모델의 성능을 평가하는 방법으로 고정된 검증 데이터셋에만 과적합 되어버리지 않도록 하는 방법
> 1. 데이터를 5개의 폴드로 나눕니다. 각 폴드는 20개의 데이터를 포함합니다.
> 2. 첫 번째 폴드를 **테스트 데이터**로 사용하고, 나머지 80개는 **학습**에 사용하여 모델을 학습합니다. 그런 다음 첫 번째 폴드에 대해 예측을 수행합니다.
> 3. 이 과정을 5번 반복하여, 각 폴드가 한 번씩 테스트 데이터로 사용되며, 해당 폴드에 대한 예측값이 생성됩니다.
> 4. **결과적으로 최종 모델은 생성되지 않고**, 각 데이터 포인트가 테스트 세트로 있을 때 예측된 값이 반환됩니다.

#### 특정 모델의 평균적인 성능을 보기 위한 목적으로 활용
---
## 교차 검증 WorkFlow

![](https://velog.velcdn.com/images/newnew_daddy/post/76491917-2cd6-49d9-a417-59efacdf64dd/image.png)

#### cross_val_score
- 특정 평가 지표를 사용하여 교차 검증을 수행하고, 각 교차 검증 반복에서 얻은 점수만 반환

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_regression

# 회귀용 데이터 생성
X, y = make_regression(
    n_samples=5643,
    n_features=6,
    n_targets=1,
    noise=50
    )

dd = pd.DataFrame(X, columns=[f'feature{i}' for i in range(1,7)])
dd['target'] = y
dd

      feature1  feature2  feature3  feature4  feature5  feature6      target
0     0.696224 -0.999701 -0.816170  0.054473  0.279942  0.255870  -27.990574
1    -0.543419 -0.435080 -0.391871  0.672659 -2.384056 -1.818116 -350.109941
2     0.964187 -1.028518 -1.112834  0.083166  1.355312  1.910333  173.629203
3     0.184502  1.057342  0.983025 -0.369407 -0.378377  1.058803  157.606054
4    -0.723961 -0.656268  1.998489 -1.764275  0.086981 -2.631567 -214.903067
...        ...       ...       ...       ...       ...       ...         ...
5638  0.642104  0.458123 -0.744413 -0.428120 -1.148319  0.311021  -44.624348
5639 -1.100371  1.038453  1.023226  1.238944  1.191104 -0.509265  181.877427
5640  0.392046 -1.134307 -0.817611  0.913114  0.655294  0.455240  136.025987
5641 -1.408927 -1.550356  0.275276 -0.200844  0.541275  0.636171 -109.267149
5642 -0.278012 -0.573617  0.429311  0.125419  0.726514 -0.850661  -88.201781

[5643 rows x 7 columns]

In [ ]:
df = pd.read_csv("dataset/random_reg.csv")

X = df[df.columns[:-1]]
y = df['target'].to_frame()

In [ ]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()

In [ ]:
from sklearn.model_selection import cross_val_score

## 교차 검증 수행
## scoring 지표 확인 -> https://scikit-learn.org/stable/modules/model_evaluation.html#scoring-parameter
scores = cross_val_score(lr, X, y, cv=5, scoring='r2')

print(f"Cross-Validation Scores: {scores}")
print(f"Mean Score: {scores.mean()}")

Cross-Validation Scores: [0.88703609 0.8944669  0.8767345  0.88150928 0.88700656]
Mean Score: 0.8853506650969981

In [ ]:
from sklearn.datasets import load_diabetes

dia = load_diabetes()
X = dia.data
y = dia.target

X.shape, y.shape

((442, 10), (442,))

In [ ]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [ ]:
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()

X = ss.fit_transform(X)

In [ ]:
from sklearn.linear_model import LinearRegression, SGDRegressor
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor

lr = LinearRegression()
sgd = SGDRegressor()
svr = SVR()
tree = DecisionTreeRegressor(max_depth=3)

In [ ]:
models = [lr, sgd, svr, tree]

for model in models:
    scores = cross_val_score(model, X, y, cv=5, scoring='r2')

    print(f"Cross-Validation Scores: {scores}")
    print(f"Mean Score: {scores.mean()}")
    print()

Cross-Validation Scores: [0.42955615 0.52259939 0.48268054 0.42649776 0.55024834]
Mean Score: 0.48231643590864215

Cross-Validation Scores: [0.42159916 0.51569659 0.48984842 0.42583822 0.54168528]
Mean Score: 0.4789335351684943

Cross-Validation Scores: [0.14739157 0.12560632 0.18203832 0.12242227 0.15658497]
Mean Score: 0.14680869160894455

Cross-Validation Scores: [0.22259211 0.43275407 0.38868188 0.20381595 0.36922476]
Mean Score: 0.32341375255322935

In [ ]:
scores = cross_val_score(lr, X, y, cv=5, scoring='r2')

print(f"Cross-Validation Scores: {scores}")
print(f"Mean Score: {scores.mean()}")

Cross-Validation Scores: [0.42955615 0.52259939 0.48268054 0.42649776 0.55024834]
Mean Score: 0.48231643590864215

#### cross_validate
- 여러 개의 평가 지표를 사용할 수 있음
- 훈련 시간(fit_time), 예측 시간(score_time) 등을 포함한 다양한 정보를 반환
- 더 유연하고 다양한 정보를 제공

In [ ]:
from sklearn.model_selection import StratifiedKFold, KFold
from sklearn.model_selection import cross_validate

spl = KFold(n_splits=4, shuffle=True, random_state=20)

cv = cross_validate(
    lr,
    X,
    y,
    cv=spl,
    scoring=['r2', 'neg_root_mean_squared_error'],
    return_train_score=True
    )


indices = [f"fold_{i}" for i in range(1,5)]

pd.DataFrame(cv, index=indices)

,fit_time,score_time,test_r2,train_r2,test_neg_root_mean_squared_error,train_neg_root_mean_squared_error
fold_1,0.000491,0.000478,0.442739,0.530518,-56.741324,-52.683264
fold_2,0.000714,0.000412,0.430694,0.536301,-56.514381,-52.904276
fold_3,0.000567,0.000409,0.543735,0.507683,-50.545864,-54.497847
fold_4,0.000356,0.000311,0.528040,0.507981,-55.445989,-53.025180

In [ ]:
cv = cross_validate(
    lr,
    X,
    y,
    cv=5,
    scoring=['r2', 'neg_root_mean_squared_error'],
    return_train_score=True
    )

indices = [f"fold_{i}" for i in range(1,6)]

pd.DataFrame(cv, index=indices)

,fit_time,score_time,test_r2,train_r2,test_neg_root_mean_squared_error,train_neg_root_mean_squared_error
fold_1,0.000524,0.000397,0.429556,0.524283,-52.724979,-53.867660
fold_2,0.000355,0.000313,0.522599,0.510321,-55.034865,-53.245898
fold_3,0.000340,0.000307,0.482681,0.523795,-56.900682,-52.769464
fold_4,0.000342,0.000297,0.426498,0.531378,-54.852042,-53.426869
fold_5,0.000335,0.000302,0.550248,0.507751,-53.946387,-53.397740

#### cross_val_predict
- 교차 검증을 통해 모델을 학습시키고, 학습된 모델로 테스트 세트의 예측값을 반환
- 예측값만 반환하며, 점수나 시간을 제공하지 않음

In [ ]:
from sklearn.model_selection import cross_val_predict

y_pred = cross_val_predict(lr, X, y, cv=5)